name: online-shopping-api
services:
  products-service-mongodb-server:
    container_name: products-service-mongodb-server
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: psdb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  orders-service-mysql-server:
    container_name: orders-service-mysql-server
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osdb
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./orders-service/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
